### ISSUE TITLE
Example of configuration file for working dictionary?

### ISSUE THREAD

**Issue by neubig** [roedoejet/mothertongues#10]
Hello, thank you for creating this great resource!

We (me, @cheyennewing, and @antonisa) are interested in creating a dictionary using MTD, but we're still slightly vague on the details here: https://mother-tongues-dictionaries.readthedocs.io/en/latest/guides.html#mtd-language-configuration-file

Do you by any chance have an example of the data files from a full working dictionary that we could use as an example? This would be very helpful.

**Comment by roedoejet** [comment]
Thanks @neubig !

Yes. my apologies, I haven't gotten around to changing all the links to the new docs. The new docs are available [here](https://docs.mothertongues.org) which should be more comprehensive and helpful than the RTD documentation. There are a series of [guides](https://docs.mothertongues.org/docs/mtd-guides) there that walk through building a dictionary.

I recommend using the [mtd-starter](https://github.com/roedoejet/mtd-starter) to get going with [preparing the data](https://docs.mothertongues.org/docs/mtd-guides-prepare), and simply committing to your fork will automatically build a GitHub Pages deployment of the dictionary, (see https://roedoejet.github.io/mtd-starter for an example.)

Then, once you have configured your dictionary, you can choose either the [mobile](https://github.com/roedoejet/mothertongues-UI) or [web](https://github.com/MotherTongues/mothertongues-UI-Web) template. There are instruction for both of those template [here](https://docs.mothertongues.org/docs/mtd-guides-ui). Finally, I have fairly detailed docs for [publishing](https://docs.mothertongues.org/docs/mtd-guides-publishing) the apps or website too, but any issues about documentation that is missing, or general bugs would be greatly appreciated! I will change all the links to the new docs soon and hopefully incorporate some of what I just wrote here into a more helpful Readme. Thanks for the nudge!

**Comment by roedoejet** [comment]
Hi again @neubig, I've changed the readme and links to the docs here: 08fdacd so I'll close this issue, but please feel free to reach out or raise another issue if there is insufficient information in the documentation.

Thanks again, I've been meaning to do this!

**Comment by neubig** [comment]
Thanks so much @roedoejet ! We'll take a look at the new docs and post if we have any additional questions.
