### ISSUE TITLE
issue encountered in install 

### ISSUE THREAD

**Issue by BaileyTrotter** [roedoejet/mothertongues#13]
Hi Aidan, 

I'm back working on my starter after a few months break and can't get it to build anymore. I couldn't figure out what was wrong, and ended up restarting it, but that didn't seem to help. I'm not sure what's changed. The issue happens in the install and looks like it might be coming from the installation of editdistance. Do you know how I could fix this?

Thank you!

-Bailey

**Comment by roedoejet** [comment]
Hi @BaileyTrotter - sorry to hear that! Can you please clarify the steps you are doing to install (ie just running `pip install mothertongues` or something else?) If you can paste the error message you get and any other information about your machine (version of Python, operating system etc) that would be very helpful.

Thanks!

**Comment by BaileyTrotter** [comment]
Hi @roedoejet, I'm pretty sure mothertongues is installed - if I run `mothertongues --version`, I get Mother `Tongues Dictionaries, version 0.18.20211130`.  I building the starter using Github Actions, and when it attempts the build, it shows an error in the install, which appears to do with editdistance:
```
Running setup.py install for editdistance: started
Running setup.py install for editdistance: finished with status 'error'
```
I'm using Python 3.10.2, on macOS 12.1.

Thank you!

**Comment by roedoejet** [comment]
Ah I see! So the error is on GitHub and not your computer then? Can you paste the link to your GitHub repo? Thanks!

**Comment by BaileyTrotter** [comment]
@roedoejet https://github.com/BaileyTrotter/mtd-starter

**Comment by roedoejet** [comment]
I have made a fix - please copy the contents of the file in: https://github.com/roedoejet/mtd-starter/blob/master/.github/workflows/main.yml into the file of the same name in your fork (https://github.com/BaileyTrotter/mtd-starter/blob/master/.github/workflows/main.yml) and then push/commit the changes, the build should work. Or if you are comfortable with git, merge the changes into your repo. Thank you very much for bringing this to my attention!
