### ISSUE TITLE
Make manifest matching insensitive to surrounding whitespace

### ISSUE THREAD

**Issue by eddieantonio** [roedoejet/mothertongues#2]
When loading the manifest:

```python
"targets": {
   "word": "  word ",
}
```

Make it insensitive to whitespace in either the definition in the manifest or in the actual data source (e.g., Google Sheet).

**Comment by wz30** [comment]
I am stuck by this step:

> You can find out more about how to create these files against the MTD configuration schema by visiting the docs 
And after looking into the docs, I still can not make my own config files. 
Can you provide any sample for that?

My references are github page, https://mother-tongues-dictionaries.readthedocs.io/en/latest/start.html and ICLDC 6 https://colab.research.google.com/drive/1Z2Isg5qAFdINpxnTnKPpa1GDOpTfSSFg#scrollTo=Xw9EfWWwNxvW.

Thanks in advance!

**Comment by roedoejet** [comment]
Thanks! this, should be fixed now 918fe48a89f78f1dd2cae55f9168fb72687d63c1
