### ISSUE TITLE
can not create correct config files for my own language

### ISSUE THREAD

**Issue by wz30** [roedoejet/mothertongues#3]
I am stuck by this step:

> You can find out more about how to create these files against the MTD configuration schema by visiting the docs

And after looking into the docs, I still can not make my own config files.
Can you provide any sample for that?

My references are github page, https://mother-tongues-dictionaries.readthedocs.io/en/latest/start.html and ICLDC 6 https://colab.research.google.com/drive/1Z2Isg5qAFdINpxnTnKPpa1GDOpTfSSFg#scrollTo=Xw9EfWWwNxvW.

Thanks in advance!

**Comment by roedoejet** [comment]
Thanks for this @wz30 - I appreciate you mentioning when something isn't clear/doesn't work. I just published a change ( 29b87db784abc5edff0677901ab0e704437d0a55 ) that includes a minimal example of the configuration files. It's building now and should appear in the documentation shortly. Would you have a look, if it works for you and you think it's clear, I'll close the issue, but let me know how you go with it.

**Comment by wz30** [comment]
Thanks for your time and more explanation.
Currently, I have two config files and one csv file as my dict data file.
And in first config file, I put:
```
    {
        "config":{
            "L1": "Danish",
            "L2": "English"
        },
        "data": [
            {
                "manifest": "/Users/LangEd/danish_csv_manifest.json",
                "resource": "/Users/LangEd/danish.csv"
            }
        ]
    }
```
And second config file
```
    {
        "name": "2017 Spreadsheet",
        "sorting": "word",
        "targets": {
            "word": "0",
            "definition": "1"
        }
    }
```


After I run mothertongues prepare /Users/LangEd/mtd-config/danish_config.json I have
KeyError: 'alphabet'.

I feel like it has something to do with this code
```
    { 
        "alphabet": ["a", "b", "c"]
        "config": {
            "L1": ...,
            "L2": ...,   
            "alphabet": ["a", "b", "c"]
        }
    }
```

But where to insert this piece of code?

**Comment by roedoejet** [comment]
Oh, interesting, I will look into that. The alphabet shouldn't be *required*, it should just be using English by default. The alphabet needs to go in the config though so change

```javascript
    {
        "config":{
            "L1": "Danish",
            "L2": "English"
        },
        "data": [
            {
                "manifest": "/Users/LangEd/danish_csv_manifest.json",
                "resource": "/Users/LangEd/danish.csv"
            }
        ]
    }
```

to (change the alphabet to whatever you want):

```javascript
    {
        "config":{
            "L1": "Danish",
            "L2": "English",
            "alphabet": ["a", "b", "c"]
        },
        "data": [
            {
                "manifest": "/Users/LangEd/danish_csv_manifest.json",
                "resource": "/Users/LangEd/danish.csv"
            }
        ]
    }
```

**Comment by roedoejet** [comment]
I found a bug where the minimal config file works programmatically but not with `mtd prepare` . I fixed it and updated here: 712c54367d4139c2a7726de83f3c8cc6d465b2d0 please try upgrading from pip: `pip install 'mothertongues==0.13.20190312' --force-reinstall` and see if it works. Thanks for pointing this out!

**Comment by roedoejet** [comment]
I changed the above to `pip install -I mothertongues` because the version I had there had a *separate* bug, mama mia. At least while mothertongues is in this alpha state, it's probably best to upgrade regularly! Doing the above with ver 0.14+ *should* work. Let me know if you have problems. Thanks!

**Comment by wz30** [comment]
Cool, thanks again and I made some progress. 
There is another issue occur by using google sheet icdlc2019. How can I make image and audio work?
My basic structure of data is 
![Screen Shot 2019-03-13 at 1 46 17 PM](https://user-images.githubusercontent.com/27601987/54302566-8a0d0c80-4597-11e9-8d6d-5616b5270c68.png)
And I also add images to the google drive and put url of the image into the cell of spreadsheet.
And add some pieces of code into the sample:
![Screen Shot 2019-03-13 at 1 56 52 PM](https://user-images.githubusercontent.com/27601987/54302805-f851cf00-4597-11e9-8751-df8b5f267f01.png)

After reloading the website deployed on Github, I do not have the corresponding image. 

Second question is for audio, the type of audio is array and it is not supported in form -- see above pic. "Form filed "array is not supported".

Sorry for keep asking questions! I am new to those tech. 

Wei

**Comment by roedoejet** [comment]
Glad that part is working now! no worries, it's good your asking questions - it's helping me find bugs and improve the guides. I've moved your recent question to a new issue, and will get back to you soon. Thanks.
