### ISSUE TITLE
Add information about how to manually export files

### ISSUE THREAD

**Issue by roedoejet** [roedoejet/mothertongues#5]
Not clear that you must run `mtd prepare` then `mtd export <config> js .` and then finally _rename_ the exported files to just `config.js` and `dict_cached.js` or change the imports in `index.html`

**Comment by kavonjon** [comment]
Created pull request #8

**Comment by roedoejet** [comment]
updated in 8667e55582601eff34c28edb50ce21e0012535b5 thanks to @kavonjon
