### ISSUE TITLE
mtd prepare doesn't refresh new csv content

### ISSUE THREAD

**Issue by mdeliw** [roedoejet/mothertongues#9]
I may be doing it wrong. I just started playing with this. I created the config, manifest, and the csv. I ran the mtd prepare . and the mtd run. The first time, it worked. Later I added more words to the csv and ran the mtd prepare . again. 

The mtd run doesn't show the latest content. Is there a step I am missing to clear the static content generated in earlier attempts?

**Comment by roedoejet** [comment]
Hi @mdeliw, thanks for posting! It sounds like you're doing the right steps, perhaps your browser is caching the old version? Can you try [disabling browser caching](https://www.technipages.com/google-chrome-how-to-completely-disable-cache) and let me know if the issue persists?

**Comment by roedoejet** [comment]
I'm going to close this - let me know if this didn't resolve your issue. Thanks!
